# .air.toml

# [build]
# bin = "your_project_name"
# exclude_dir = ["assets", "frontend", "node_modules"]

# [build.command]
# go = ["build", "-o", "bin/your_project_name"]

# [log]
# format = "time"

# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o ./tmp/main ."
  bin = "./tmp/main"
  delay = 0 # ms
  exclude_dir = ["assets", "tmp", "vendor"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_regex = ["_test\\.go"]